INSERT INTO PERSONS (id, nascimento, nome) VALUES (1, '1990-06-13','José');
INSERT INTO PERSONS (id, nascimento, nome) VALUES (2, '1992-03-11','Francisco');
INSERT INTO PERSONS (id, nascimento, nome) VALUES (3, '1980-01-22','Babi');
INSERT INTO PERSONS (id, nascimento, nome) VALUES (4, '1973-06-28','Ítalo');
INSERT INTO PERSONS (id, nascimento, nome) VALUES (5, '2001-10-01','Carlos');
INSERT INTO ENDERECOS (id, CEP,CIDADE, IS_MAIN, LOGRADOURO, NUMERO, PERSON_ID) 
VALUES (1, '58900-000','Jabuticabal',null,'Rua da Paz',50,1);
INSERT INTO ENDERECOS (id, CEP,CIDADE, IS_MAIN, LOGRADOURO, NUMERO, PERSON_ID) 
VALUES (2, '68900-000','Juriti',null,'Rua da Guerra',321,1);
INSERT INTO ENDERECOS (id, CEP,CIDADE, IS_MAIN, LOGRADOURO, NUMERO, PERSON_ID) 
VALUES (3, '78000-000','Itapipoca',true,'Rua da Sorte',467,1);
INSERT INTO ENDERECOS (id, CEP,CIDADE, IS_MAIN, LOGRADOURO, NUMERO, PERSON_ID) 
VALUES (4, '18900-000','Atibaia',null,'Rua do Trevo',150,2);
INSERT INTO ENDERECOS (id, CEP,CIDADE, IS_MAIN, LOGRADOURO, NUMERO, PERSON_ID) 
VALUES (5, '28900-000','Itatiba',null,'Rua da Luz',132,2);
INSERT INTO ENDERECOS (id, CEP,CIDADE, IS_MAIN, LOGRADOURO, NUMERO, PERSON_ID) 
VALUES (6, '38000-000','Laguna',true,'Rua do Padre',247,2);

